from __future__ import annotations

import json
import unittest
from pathlib import Path

from frontmatter import frontmatter_for


ROOT = Path(__file__).resolve().parents[1]
SKILL = ROOT / "epac-selection-display" / "SKILL.md"
ADAPTER = ROOT / "skills" / "epac-selection-display" / "SKILL.md"
INDEX = ROOT / "skills.json"


class EpacSelectionDisplaySkillTest(unittest.TestCase):
    def setUp(self) -> None:
        self.text = SKILL.read_text(encoding="utf-8")
        self.compact = " ".join(self.text.split())
        self.frontmatter = frontmatter_for(SKILL)

    def test_activation_and_nontrigger_are_discriminating(self) -> None:
        description = self.frontmatter["description"]
        for phrase in (
            "EPAC element, molecule, construction receipt, comparison result",
            "selectable WebMCP skill",
            "Do not load",
            "select EPAC or a UCNS candidate as canon",
        ):
            self.assertIn(phrase, description)

    def test_display_selection_never_promotes_status(self) -> None:
        for phrase in (
            "display selection != canon selection",
            "A display preference cannot ratify a candidate",
            "selection_effect",
            "not organization canon",
        ):
            self.assertIn(phrase, self.text)

    def test_handle_and_provisional_source_boundaries_are_explicit(self) -> None:
        self.assertIn("The EPAC handle is despecified here", self.text)
        self.assertIn("no independent authoritative source repository", self.compact)
        self.assertIn("base commit plus content digests", self.compact)

    def test_target_receipt_and_representation_are_verified(self) -> None:
        for phrase in (
            "Selection record",
            "Resolve the user-facing target to one exact registered identifier",
            "independently replay it",
            "receipt-backed summary rather than inventing a visual projection",
            "Emit the evidence packet beside the display",
        ):
            self.assertIn(phrase, self.text)

    def test_webmcp_remains_a_read_only_handoff(self) -> None:
        for phrase in (
            "require repository selection before skill selection",
            "require an explicit Send",
            "remote MCP server remains a read-only registry",
            "separately authorized tools",
        ):
            self.assertIn(phrase, self.text)

    def test_sealed_comparison_and_invented_geometry_are_blocked(self) -> None:
        self.assertIn("construction remains blind to sealed known-shape labels", self.compact)
        self.assertIn("must not infer positions, couplings", self.compact)
        self.assertIn("Opening sealed comparison labels during construction", self.text)

    def test_index_and_adapter_expose_the_canonical_skill(self) -> None:
        index = json.loads(INDEX.read_text(encoding="utf-8"))
        entry = next(item for item in index["skills"] if item["name"] == "epac-selection-display")
        self.assertEqual("procedural", entry["kind"])
        self.assertEqual(self.frontmatter["description"], entry["description"])

        adapter = ADAPTER.read_text(encoding="utf-8")
        self.assertIn("Generated by tools/build_codex_plugin_skills.py", adapter)
        self.assertIn("../../epac-selection-display/SKILL.md", adapter)


if __name__ == "__main__":
    unittest.main()
