from __future__ import annotations

import unittest
from pathlib import Path

from frontmatter import frontmatter_for


ROOT = Path(__file__).resolve().parents[1]
SKILL = ROOT / "gonol-build" / "SKILL.md"
ADAPTER = ROOT / "skills" / "gonol-build" / "SKILL.md"


class GonolBuildSkillTest(unittest.TestCase):
    def setUp(self) -> None:
        self.text = SKILL.read_text(encoding="utf-8")
        self.frontmatter = frontmatter_for(SKILL)

    def test_activation_and_nontrigger_are_concrete(self) -> None:
        description = self.frontmatter["description"]
        for phrase in (
            "character, word, morphology, definition",
            "punctuation-function",
            "recursive gonols",
            "Do not load",
            "ordinary prose editing",
        ):
            self.assertIn(phrase, description)

    def test_routes_authority_to_current_ucns(self) -> None:
        self.assertIn("Resolve the current UCNS commit or PR", self.text)
        self.assertIn("Repo-local UCNS authority may evolve", self.text)
        self.assertIn("does not copy a frozen UCNS snapshot", self.text)

    def test_closure_and_atomic_promotion_are_preserved(self) -> None:
        for phrase in (
            "relation enters the construction",
            "closure with source identity and receipt",
            "atomic participant at another scale",
            "indivisible for participation at the consuming scale",
            "Do not materialize an all-pairs relationship graph",
        ):
            self.assertIn(phrase, self.text)

    def test_function_application_refuses_inference(self) -> None:
        for phrase in (
            "caller-supplied, occurrence-addressed application context",
            "Never infer adjacency, precedence, grammatical role",
            "Replay against the same authoritative table",
            "Do not promote structural survival into parsing",
        ):
            self.assertIn(phrase, self.text)

    def test_completion_requires_full_run_and_replay(self) -> None:
        for phrase in (
            "Admit the complete declared source",
            "let it reach its natural terminal condition",
            "Independently reconstruct or replay",
            "Compare byte-for-byte",
            "A historical receipt remains",
        ):
            self.assertIn(phrase, self.text)

    def test_deprecated_morphology_cannot_return(self) -> None:
        self.assertIn("deprecated omega/phi/psi cores", self.text)
        self.assertIn("bone/flesh categories", self.text)
        self.assertIn("carrier-LCM as the universal language", self.text)

    def test_hmmm_and_claim_boundaries_are_required(self) -> None:
        self.assertIn("claims not supported:", self.text)
        self.assertIn("hmmm:", self.text)
        self.assertIn("complete English morphology law", self.text)
        self.assertIn("Do not translate `SURVIVED` into proved", self.text)

    def test_hmmm_blocks_promotion_not_candidate_construction(self) -> None:
        self.assertIn("ban on unqualified", self.text)
        self.assertIn("not as a ban on declared candidate construction", self.text)
        self.assertIn("Constructing a declared, falsifiable candidate is required progress", self.text)
        self.assertIn("`hmmm` blocks unqualified promotion", self.text)
        self.assertIn("does not block experimentation or", self.text)
        self.assertIn("which recursive-gonol candidate, if any, later becomes selected canon", self.text)
        self.assertNotIn("the first complete recursive-gonol relation constructor beyond definition", self.text)

    def test_codex_adapter_points_to_canonical_skill(self) -> None:
        text = ADAPTER.read_text(encoding="utf-8")
        self.assertIn("Generated by tools/build_codex_plugin_skills.py", text)
        self.assertIn("../../gonol-build/SKILL.md", text)


if __name__ == "__main__":
    unittest.main()
