# ratios: loc_comments=64:9 imports_exports=5:5 calls_definitions=33:5
#!/usr/bin/env python3
"""Build thin Codex plugin adapters for every canonical skill-lib skill.

Usage guidance:
    python tools/build_codex_plugin_skills.py --check
    python tools/build_codex_plugin_skills.py --apply

Canonical skill doctrine remains in ``<skill-name>/SKILL.md``. Generated files
under ``skills/`` contain only discovery metadata and an instruction to load
that canonical source. Do not edit generated adapters by hand.
"""

from __future__ import annotations

import argparse
import json
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
INDEX = ROOT / "skills.json"
OUTPUT = ROOT / "skills"
HEADER = "<!-- Generated by tools/build_codex_plugin_skills.py; do not edit. -->"


def adapter(skill: dict[str, object]) -> str:
    name = str(skill["name"])
    description = json.dumps(str(skill["description"]), ensure_ascii=False)
    canonical_path = str(skill["path"])
    return (
        f"---\nname: {name}\ndescription: {description}\n---\n\n"
        f"{HEADER}\n\n"
        f"Read and follow `../../{canonical_path}` completely before acting. "
        "That file is the canonical skill; this adapter only exposes it through "
        "the Codex plugin skill directory.\n"
    )


def expected() -> dict[Path, str]:
    data = json.loads(INDEX.read_text(encoding="utf-8"))
    return {
        OUTPUT / str(skill["name"]) / "SKILL.md": adapter(skill)
        for skill in data["skills"]
    }


def drift() -> list[str]:
    wanted = expected()
    findings: list[str] = []
    actual = set(OUTPUT.glob("*/SKILL.md")) if OUTPUT.exists() else set()
    for path, content in wanted.items():
        if not path.exists():
            findings.append(f"missing: {path.relative_to(ROOT)}")
        elif path.read_text(encoding="utf-8") != content:
            findings.append(f"drift: {path.relative_to(ROOT)}")
    for path in sorted(actual - set(wanted)):
        findings.append(f"unexpected: {path.relative_to(ROOT)}")
    return findings


def apply() -> None:
    wanted = expected()
    OUTPUT.mkdir(exist_ok=True)
    actual_dirs = {path.parent for path in OUTPUT.glob("*/SKILL.md")}
    wanted_dirs = {path.parent for path in wanted}
    for directory in sorted(actual_dirs - wanted_dirs):
        shutil.rmtree(directory)
    for path, content in wanted.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--apply", action="store_true")
    args = parser.parse_args()

    if args.apply:
        apply()
    findings = drift()
    if findings:
        print("\n".join(findings))
        return 1
    print(f"Codex plugin adapters: pass ({len(expected())} skills)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
# ratios: loc_comments=64:9 imports_exports=5:5 calls_definitions=33:5
